name: money_kylin
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl: ^0.16.0
  fluttertoast: ^4.0.1
  sqflite: ^1.3.2+4
  path_provider: ^1.6.28
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.4
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1+1
  build_runner:

flutter:
  uses-material-design: true
